"""Generadores de datos sinteticos para tests.

Genera CSV con la misma forma que un export real de LibreView: dos lineas de preambulo,
cabecera ancha, columnas localizables y filas de distinto Record Type.
"""

from __future__ import annotations

import math
from collections.abc import Sequence
from datetime import datetime, timedelta

HEADERS_EN = [
    "Device",
    "Serial Number",
    "Device Timestamp",
    "Record Type",
    "Historic Glucose mg/dL",
    "Scan Glucose mg/dL",
    "Non-numeric Rapid-Acting Insulin",
    "Rapid-Acting Insulin (units)",
    "Non-numeric Food",
    "Carbohydrates (grams)",
    "Carbohydrates (servings)",
    "Non-numeric Long-Acting Insulin",
    "Long-Acting Insulin Value (units)",
    "Notes",
    "Strip Glucose mg/dL",
    "Ketone mmol/L",
    "Meal Insulin (units)",
    "Correction Insulin (units)",
    "User Change Insulin (units)",
]

HEADERS_ES = [
    "Dispositivo",
    "Número de serie",
    "Sello de tiempo del dispositivo",
    "Tipo de registro",
    "Histórico de glucosa mg/dL",
    "Glucosa escaneada mg/dL",
    "Insulina de acción rápida no numérica",
    "Insulina de acción rápida (unidades)",
    "Alimento no numérico",
    "Carbohidratos (gramos)",
    "Carbohidratos (raciones)",
    "Insulina de acción prolongada no numérica",
    "Insulina de acción prolongada (unidades)",
    "Notas",
    "Glucosa de tira mg/dL",
    "Cetona mmol/L",
    "Insulina de comida (unidades)",
    "Insulina de corrección (unidades)",
    "Cambio de insulina del usuario (unidades)",
]

_IDX = {name: i for i, name in enumerate(HEADERS_EN)}


def fmt_ts(dt: datetime, order: str = "DMY", sep: str = "-") -> str:
    if order == "DMY":
        d = f"{dt.day:02d}{sep}{dt.month:02d}{sep}{dt.year}"
    elif order == "MDY":
        d = f"{dt.month:02d}{sep}{dt.day:02d}{sep}{dt.year}"
    elif order == "YMD":
        d = f"{dt.year}{sep}{dt.month:02d}{sep}{dt.day:02d}"
    else:
        raise ValueError(order)
    return f"{d} {dt.hour:02d}:{dt.minute:02d}"


def _blank_row(device: str, serial: str, ts: str, record_type: int) -> list[str]:
    row = [""] * len(HEADERS_EN)
    row[0], row[1], row[2], row[3] = device, serial, ts, str(record_type)
    return row


def build_libreview_csv(
    *,
    readings: Sequence[tuple[datetime, float]],
    serial: str = "ABC123",
    device: str = "FreeStyle Libre 2 Plus",
    date_order: str = "DMY",
    headers: Sequence[str] = HEADERS_EN,
    delimiter: str = ",",
    scans: Sequence[tuple[datetime, float]] = (),
    foods: Sequence[tuple[datetime, float | None, str | None]] = (),
    unit_label: str = "mg/dL",
    preamble_lines: int = 1,
) -> bytes:
    """Construye un CSV con la forma de un export de LibreView."""
    hdr = [h.replace("mg/dL", unit_label) for h in headers]
    lines: list[list[str]] = []
    for _ in range(preamble_lines):
        lines.append(["Glucose Data", "Generated on", "08-08-2026 10:00", "Generated by", "Test"])
    lines.append(list(hdr))

    for ts, val in readings:
        row = _blank_row(device, serial, fmt_ts(ts, date_order), 0)
        row[_IDX["Historic Glucose mg/dL"]] = f"{val:g}"
        lines.append(row)
    for ts, val in scans:
        row = _blank_row(device, serial, fmt_ts(ts, date_order), 1)
        row[_IDX["Scan Glucose mg/dL"]] = f"{val:g}"
        lines.append(row)
    for ts, carbs, note in foods:
        row = _blank_row(device, serial, fmt_ts(ts, date_order), 5)
        if carbs is not None:
            row[_IDX["Carbohydrates (grams)"]] = f"{carbs:g}"
        if note:
            row[_IDX["Notes"]] = note
        lines.append(row)

    out = "\n".join(delimiter.join(c for c in row) for row in lines)
    return out.encode("utf-8")


def synth_series(
    start: datetime,
    *,
    hours: float = 24,
    resolution_min: int = 15,
    baseline: float = 95.0,
    meals: Sequence[tuple[datetime, float, float]] = (),
) -> list[tuple[datetime, float]]:
    """Serie sintetica: basal + respuestas postprandiales con forma gamma.

    ``meals`` son tuplas ``(t_comida, amplitud_mgdl, minutos_hasta_pico)``.
    Deterministica: sin ruido aleatorio, para que los tests sean reproducibles.
    """
    n = int(hours * 60 / resolution_min)
    out: list[tuple[datetime, float]] = []
    for i in range(n + 1):
        t = start + timedelta(minutes=i * resolution_min)
        val = baseline
        for meal_t, amp, ttp in meals:
            dt_min = (t - meal_t).total_seconds() / 60.0
            if dt_min <= 0:
                continue
            # Curva gamma normalizada a pico=amp en t=ttp.
            k = 2.0
            theta = ttp / k
            val += amp * (dt_min / ttp) ** k * math.exp(k - dt_min / theta)
        out.append((t, round(val, 1)))
    return out
