"""catalogo canonico de alimentos

Revision ID: 3aae8fe4dd76
Revises: 40282063a562
Create Date: 2026-08-09 09:35:38.348005

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3aae8fe4dd76'
down_revision: str | None = '40282063a562'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Anadido a mano: autogenerate no detecta extensiones. pg_trgm da la busqueda por
    # similitud que usa el resolutor para sugerir alimentos ante texto libre, y es
    # requisito del indice GIN 'ix_food_alias_trgm' que se crea mas abajo.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('canonical_name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('is_recipe', sa.Boolean(), nullable=False),
    sa.Column('default_portion_g', sa.Float(), nullable=True),
    sa.Column('portion_unit', sa.String(length=32), nullable=True),
    sa.Column('fdc_query_hint', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('food_alias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('alias', sa.String(length=160), nullable=False),
    sa.Column('normalized', sa.String(length=160), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized', 'user_id', name='uq_food_alias_normalized_user')
    )
    op.create_index('ix_food_alias_trgm', 'food_alias', ['normalized'], unique=False, postgresql_using='gin', postgresql_ops={'normalized': 'gin_trgm_ops'})
    op.create_table('food_nutrient',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('nutrient', sa.String(length=24), nullable=False),
    sa.Column('amount_per_100g', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=120), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('food_id', 'nutrient')
    )
    op.create_table('food_source_map',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('external_name', sa.Text(), nullable=True),
    sa.Column('matched_by', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id')
    )
    op.create_table('recipe_component',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_food_id', sa.UUID(), nullable=False),
    sa.Column('component_food_id', sa.UUID(), nullable=False),
    sa.Column('mass_fraction', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['component_food_id'], ['food.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_food_id'], ['food.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_food_id', 'component_food_id')
    )
    op.create_table('user_food_portion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=48), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('n_observations', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'food_id', 'label')
    )
    op.add_column('meal_item', sa.Column('food_id', sa.UUID(), nullable=True))
    op.add_column('meal_item', sa.Column('resolution_confidence', sa.Float(), nullable=True))
    op.add_column('meal_item', sa.Column('resolution_method', sa.String(length=24), nullable=True))
    op.create_foreign_key(None, 'meal_item', 'food', ['food_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meal_item', type_='foreignkey')
    op.drop_column('meal_item', 'resolution_method')
    op.drop_column('meal_item', 'resolution_confidence')
    op.drop_column('meal_item', 'food_id')
    op.drop_table('user_food_portion')
    op.drop_table('recipe_component')
    op.drop_table('food_source_map')
    op.drop_table('food_nutrient')
    op.drop_index('ix_food_alias_trgm', table_name='food_alias', postgresql_using='gin', postgresql_ops={'normalized': 'gin_trgm_ops'})
    op.drop_table('food_alias')
    op.drop_table('food')
    # ### end Alembic commands ###
