"""esquema inicial fase 1

Revision ID: 40282063a562
Revises: 
Create Date: 2026-08-08 12:01:08.894650

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '40282063a562'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('cgm_sensor_session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vendor', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('device_serial_hash', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('native_resolution_min', sa.SmallInteger(), nullable=True),
    sa.Column('n_readings', sa.Integer(), nullable=False),
    sa.Column('step_vs_previous_mgdl', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_serial_hash', 'started_at')
    )
    op.create_table('ingest_batch',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vendor', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_filename', sa.Text(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('is_official_api', sa.Boolean(), nullable=False),
    sa.Column('legal_basis', sa.String(length=64), nullable=False),
    sa.Column('assumed_timezone', sa.String(length=64), nullable=True),
    sa.Column('detected_date_order', sa.String(length=8), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glucose_reading',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ts_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tz_offset_min', sa.SmallInteger(), nullable=False),
    sa.Column('value_mgdl', sa.Float(), nullable=False),
    sa.Column('source_record', sa.String(length=16), nullable=False),
    sa.Column('quality_flags', sa.Integer(), nullable=False),
    sa.Column('ingest_batch_id', sa.UUID(), nullable=False),
    sa.CheckConstraint('value_mgdl > 0', name='ck_glucose_positive'),
    sa.ForeignKeyConstraint(['ingest_batch_id'], ['ingest_batch.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['cgm_sensor_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'ts_utc', 'session_id')
    )
    op.create_index('ix_glucose_reading_ts_brin', 'glucose_reading', ['ts_utc'], unique=False, postgresql_using='brin')
    op.create_index('ix_glucose_reading_user_ts', 'glucose_reading', ['user_id', 'ts_utc'], unique=False)
    op.create_table('meal',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tz_offset_min', sa.SmallInteger(), nullable=False),
    sa.Column('meal_type', sa.String(length=16), nullable=False),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('eating_duration_min', sa.SmallInteger(), nullable=True),
    sa.Column('order_pattern', sa.String(length=16), nullable=False),
    sa.Column('photo_object_key', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('entry_completeness', sa.Float(), nullable=True),
    sa.Column('ingest_batch_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingest_batch_id'], ['ingest_batch.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meal_user_time', 'meal', ['user_id', 'consumed_at'], unique=False)
    op.create_table('meal_glucose_response',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('exclusion_reasons', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('degradation_reasons', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('baseline_mgdl', sa.Float(), nullable=True),
    sa.Column('baseline_sd', sa.Float(), nullable=True),
    sa.Column('baseline_n', sa.SmallInteger(), nullable=True),
    sa.Column('peak_mgdl', sa.Float(), nullable=True),
    sa.Column('peak_delta_mgdl', sa.Float(), nullable=True),
    sa.Column('time_to_peak_min', sa.Float(), nullable=True),
    sa.Column('peak_underestimated', sa.Boolean(), nullable=True),
    sa.Column('iauc_120', sa.Float(), nullable=True),
    sa.Column('iauc_180', sa.Float(), nullable=True),
    sa.Column('iauc_net_120', sa.Float(), nullable=True),
    sa.Column('auc_total_120', sa.Float(), nullable=True),
    sa.Column('time_above_baseline_min', sa.Float(), nullable=True),
    sa.Column('time_to_return_baseline_min', sa.Float(), nullable=True),
    sa.Column('cv_pct', sa.Float(), nullable=True),
    sa.Column('curve_shape', sa.String(length=16), nullable=True),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('max_gap_min', sa.Float(), nullable=True),
    sa.Column('n_points', sa.SmallInteger(), nullable=True),
    sa.Column('resolution_min', sa.SmallInteger(), nullable=True),
    sa.Column('hour_local', sa.SmallInteger(), nullable=True),
    sa.Column('prev_meal_gap_min', sa.Float(), nullable=True),
    sa.Column('next_meal_gap_min', sa.Float(), nullable=True),
    sa.Column('sensor_age_hours', sa.Float(), nullable=True),
    sa.Column('vendor', sa.String(length=32), nullable=True),
    sa.Column('algorithm_version', sa.String(length=32), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['cgm_sensor_session.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_id')
    )
    op.create_table('meal_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('raw_label', sa.Text(), nullable=False),
    sa.Column('quantity_value', sa.Float(), nullable=True),
    sa.Column('quantity_unit', sa.String(length=32), nullable=True),
    sa.Column('quantity_low', sa.Float(), nullable=True),
    sa.Column('quantity_high', sa.Float(), nullable=True),
    sa.Column('preparation', sa.String(length=32), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('user_corrected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_item')
    op.drop_table('meal_glucose_response')
    op.drop_index('ix_meal_user_time', table_name='meal')
    op.drop_table('meal')
    op.drop_index('ix_glucose_reading_user_ts', table_name='glucose_reading')
    op.drop_index('ix_glucose_reading_ts_brin', table_name='glucose_reading', postgresql_using='brin')
    op.drop_table('glucose_reading')
    op.drop_table('ingest_batch')
    op.drop_table('cgm_sensor_session')
    op.drop_table('app_user')
    # ### end Alembic commands ###
